name: docs-environment

channels:
  - conda-forge
  - cadquery

dependencies:
  - python=3.8
  - pyparsing~=2.4.7
  - cadquery=2.1
  - pytest
  - plotly
  - scipy
  - numpy
  - matplotlib
  - pillow
  - pip:
      - sympy
      - plasma_boundaries
      - sphinx-autodoc-typehints
      - sphinxcadquery
      - defusedxml
      - jupyter-cadquery
