# Python CircleCI 2.0 configuration file
##
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2
jobs:
  # test:
  build:
    docker:
      - image: ghcr.io/fusion-energy/paramak:dependencies
    steps:
      - checkout
      - run:
          name: install
          command: |
            python setup.py install

      - run:
          name: run utils tests
          command: 
            pytest tests/test_utils.py -v --cov=paramak --cov-append --cov-report term --cov-report xml --junitxml=test-reports/junit.xml

      - run:
          name: run shape tests
          command:
            pytest tests/test_shape.py -v --cov=paramak --cov-append --cov-report term --cov-report xml --junitxml=test-reports/junit.xml

      - run:
          name: run Reactor tests
          command:
            pytest tests/test_reactor.py -v --cov=paramak --cov-append --cov-report term --cov-report xml --junitxml=test-reports/junit.xml

      - run:
          name: run parametric_shapes tests
          command:
            pytest tests/test_parametric_shapes/ -v --cov=paramak --cov-append --cov-report term --cov-report xml --junitxml=test-reports/junit.xml

      - run:
          name: run parametric_components tests
          command:
            pytest tests/test_parametric_components/ -v --cov=paramak --cov-append --cov-report term --cov-report xml --junitxml=test-reports/junit.xml

      - run:
          name: run parametric_reactors tests
          command:
            pytest tests/test_parametric_reactors/ -v --cov=paramak --cov-append --cov-report term --cov-report xml --junitxml=test-reports/junit.xml

      - store_test_results:
          path: test-reports

      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - build
      # - test
      # - build-deploy-master:
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only: master
      # - build-deploy-dev:
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only: develop
