
# This CI will lauch a Docker image that contains all the dependencies required
# within that image the pytest test suite is run 


name: CI with install

on:
  pull_request:    
    branches:
    - develop
    - main
 
jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fusion-energy/paramak:dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: install package
        run: |
          python setup.py install

      - name: Run test_utils
        run: |
          pytest tests/test_utils.py -v --cov=paramak --cov-append --cov-report term --cov-report xml
      - name: Run test_shape
        run: |
          pytest tests/test_shape.py -v --cov=paramak --cov-append --cov-report term --cov-report xml
      - name: Run test_reactor
        run: |
          pytest tests/test_reactor.py -v --cov=paramak --cov-append --cov-report term --cov-report xml
      - name: Run test_h5m_export
        run: |
          pytest tests/test_h5m_export.py -v --cov=paramak --cov-append --cov-report term --cov-report xml
      - name: Run test_parametric_shapes
        run: |
          pytest tests/test_parametric_shapes/ -v --cov=paramak --cov-append --cov-report term --cov-report xml
      - name: Run test_parametric_components
        run: |
          pytest tests/test_parametric_components/ -v --cov=paramak --cov-append --cov-report term --cov-report xml
      - name: Run test_parametric_reactors
        run: |
          pytest tests/test_parametric_reactors/ -v --cov=paramak --cov-append --cov-report term --cov-report xml
