name: Test demos

# Controls when the action will run.
on:
  # Triggers the workflow on push requests to main or develop branches
  pull_request:
    branches:
      - main
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fusion-energy/paramak:dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup paramak
        run: |
          pip install .[tests]

      - name: Run the notebooks
        run: |
          pytest tests_examples -v
